<?php
define("COMPANY_NAME","Test Company");
define("COMPANY_PHONE_NUMBER", "1-800-838-8651");

print '  <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"> ';
print ' 
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="content-type" content="text/html; charset=UTF-8">
    <title>Terms and Conditions</title>
    <style type="text/css">
        div {
            font-family: Verdana;
            font-size: 13px;
            line-height: 1.5;
            color: #000000;
            margin: auto;
            width: 700px;
        }
        h3{
            text-align: center;
        }
        h4{
            text-align: center;
        }
    </style>
</head>
<body>
<div align="justify">
    <p>
    </p><h3>Payter Terms and Conditions:</h3>
    <p></p>
    <p>
	In consideration of the mutual promises contained herein and other good and valuable consideration, the receipt and sufficiency of which is hereby acknowledged, Payter and Merchant, intending to be legally bound, do hereby agree as follows:
		<br>1.&#160;&#160;&#160;&#160;&#160;	<b>Laws, Rules, and Procedures.</b> Merchant acknowledges receipt of and agrees to comply with all Payter rules and procedures pertaining to Payter provided services ("<b>Payter Procedures</b>"). The Payter Procedures may be amended from time to time by Payter, and Merchant agrees to be bound by such amendments. Merchant further agrees to comply with, and be bound by, all applicable state or federal laws, rules, regulations, orders, guidelines, operating circulars and pronouncements, affecting checks ("<b>Checks</b>") (as that term is defined in Federal Reserve Board Regulation CC ("<b>Reg CC</b>")) and drafts, credit card, and Automated Clearing House ("<b>ACH</b>") transactions, including, but not limited to, all rules and procedural guidelines established by the Federal Trade Commission ("<b>FTC</b>"), the Board of Governors of the Federal Reserve, National Check Exchange ("<b>NCE</b>"), Small Value Payments Company ("<b>SVPCo</b>"), Viewpointe, Endpoint Exchange, the National Automated Clearing House Association ("<b>NACHA</b>"), Electronic Check Clearing House Organization ("<b>ECCHO</b>") and any other clearinghouse or other organization in which Payter\'s bank is a member or to which rules Payter\'s bank has agreed to be bound. These rules and regulations (collectively the "<b>Rules</b>") and laws are incorporated herein by reference. In the event of conflict between the terms of this Agreement and the Rules, the Rules will control. Merchant acknowledges that Merchant has a copy of or has access to a copy of the Rules. It is Merchant\'s responsibility to ensure that the transactions it engages in under Payter provided services comply with U.S. law, including, but not limited to, sanctions enforced by the Office of Foreign Assets Control ("<b>OFAC</b>") and all rules and regulations promulgated by the Federal Trade Commission ("<b>FTC</b>"). It shall further be Merchant\'s responsibility to obtain information regarding such OFAC enforced sanctions. (This information may be obtained directly from the OFAC Compliance Hotline at (800) 540-OFAC). Restricted transactions as defined in Federal Reserve Regulation GG are prohibited from being processed through Payter provided services or relationship. Restricted transactions generally include, but are not limited to, those in which credit, electronic fund transfers, checks, or drafts are knowingly accepted by gambling businesses in connection with the participation by others in unlawful Internet gambling. Payter will charge Merchant with any fines incurred as a result of non-compliance by Merchant and Merchant agrees to fully reimburse and/or indemnify Payter for such charges or fines. The duties of Merchant set forth in the following paragraphs of this Agreement in no way limit the requirement of complying with the Rules. Terms not otherwise defined in this Agreement shall have the meaning ascribed to those terms in the Rules.
		<br>2.&#160;&#160;&#160;&#160;&#160;	<b>Merchant Duties.</b> Merchant agrees to establish and maintain one or more accounts with a financial institution to facilitate payment of available funds from the deposit made by Merchant ("<b>Depository Account</b>"). Merchant will provide Payter the Depository Account information as part of the Merchant set-up process by completing the Merchant Application ("<b>Merchant Application</b>"). If Merchant changes the Depository Account, Merchant agrees to provide one week\'s advance written notice to Payter regarding such change. Any Merchant obligations and authorizations as to the former Depository Account shall continue forward to the new Depository Account.
		<br>3.&#160;&#160;&#160;&#160;&#160;	<b>Access to Payter Provided Services.</b> Merchant acknowledges that it is solely responsible for obtaining and maintaining at its own expense, all hardware and software needed to access Payter provided services. Payter is not responsible for, and Merchant hereby releases Payter from any and all claims or damages resulting from, or related to, any computer virus or related problems that may be associated with using electronic mail or the Internet as well as failures of or interruptions in any electrical, telephone or Internet services.
		All right, title and interest in and to (a) any and all computer programs, including, but not limited to, the object and source codes therefore, and any and all updates, upgrades, fixes and enhancements thereto and any and all documentation, user guides and instructions pertaining thereto (everything in this clause (a), collectively, "Software"), (b) the Payter Procedures and (c) any and all users guides, instructions and other documentation provided to, or used by, Merchant in connection with Payter provided services (everything in this clause (c) together with the Payter Procedures manual, collectively, the "<b>Documentation</b>") shall be, and remain, the property of Payter or any third party software provider, as applicable. Unless otherwise expressly authorized, Merchant may not (aa) copy, reproduce, transmit, retransmit, disseminate, display, publish, sell, broadcast, circulate, distribute, transfer, assign, commercially exploit, reverse engineer, reverse compile or create derivative works of, the Software in any form or (bb) copy, reproduce, transmit, retransmit, disseminate, display, publish, sell, broadcast, circulate, distribute, transfer, assign, commercially exploit the Documentation.
		<br>4.&#160;&#160;&#160;&#160;&#160;	<b>Security.</b>
		<br>(a)&#160;&#160;&#160;&#160;&#160;			Payter may also provide Merchant with, or require Merchant to establish, a User ID and passwords and other procedures (collectively, "<b>Security Procedures</b>") to access Payter provided services. The specific Security Procedures will be described in the Payter Procedures. Merchant agrees to, at all times, (i) safeguard the confidentiality and security of the Payter Procedures, Security Procedures and all other proprietary property or information Payter provides to Merchant in connection with Payter provided services, and (ii) notify Payter immediately if Merchant has any reason to believe the security or confidentiality required by this provision has been or may be breached. Merchant acknowledges, understands and agrees the Security Procedures are not designed for the detection of errors. Payter is not, and will not be, obligated to detect errors by Merchant or others, even if Payter takes certain actions from time to time to do so. Merchant is solely responsible for providing for and maintaining the physical, electronic, procedural, administrative, and technical security of data and systems in Merchant\'s possession or under Merchant\'s control.
		<br>(b)&#160;&#160;&#160;&#160;&#160;			Merchant agrees to educate representatives of Merchant authorized to use Payter provided services ("<b>Authorized Merchant Representative(s)</b>"), agents, and employees as to the risks of fraud and to train such persons to avoid such risks. Merchant agrees that Payter is not responsible for any losses, injuries, or harm incurred by Merchant as a result of any electronic, e-mail, or internet fraud.
		<br>(c)&#160;&#160;&#160;&#160;&#160;			In the event of a breach of the Security Procedure, Merchant agrees to assist Payter in determining the manner and source of the breach. Such assistance shall include, but shall not be limited to, providing Payter or Payter\'s agent access to Merchant\'s hard drive, storage media and devices, systems and any other equipment or device that was used in breach of the Security Procedure. Merchant further agrees to provide to Payter any analysis of such equipment, device, or software or any report of such analysis performed by Merchant, Merchant\'s agents, law enforcement agencies, or any other third party. Failure of Merchant to assist Payter shall be an admission by Merchant that the breach of the Security Procedure was caused by a person who obtained access to transmitting facilities of Merchant or who obtained information facilitating the breach of the Security Procedure from Merchant and not from a source controlled by Payter.
		<br>5.&#160;&#160;&#160;&#160;&#160;	<b>Errors, Cancellations and Amendments to Transactions.</b> Merchant shall notify Payter immediately of any transaction Merchant discovers it has initiated or authorized in error. Payter shall use its best efforts to act on a request by Merchant to cancel or amend a transaction prior to transmitting it to the ACH, Check, or credit card system, but shall have no liability if such cancellation is not effected. Merchant shall reimburse Payter for any expenses, losses, or damages Payter may incur in effecting or attempting to affect Merchant\'s request for the reversal of a transaction.
		<br>6.&#160;&#160;&#160;&#160;&#160;	<b>Reserve.</b> In the event Payter, at its discretion, requires Merchant to maintain a reserve with Payter, Merchant agrees to execute a "<b>Reserve Account Addendum</b>" in order to continue using Payter provided services. The reserve shall be in an amount determined solely by Payter and agreed upon by Merchant in the Reserve Account Addendum. Merchant grants Payter a security interest in any monies in reserve to enable Payter to enforce any obligation owed by Merchant under this Agreement without notice or demand to Merchant.
		<br>7.&#160;&#160;&#160;&#160;&#160;	<b>Account Reconciliation.</b> Merchant is responsible for detecting and reporting to Payter any discrepancy between Merchant\'s records and the records that Payter provides to Merchant via Payter reporting. If Merchant does not detect and notify Payter of such a discrepancy within 10 days of transmitting the file to Payter, then such transactions shall be considered correct, and Merchant shall be precluded from asserting such error or discrepancy against Payter.
		<br>8.&#160;&#160;&#160;&#160;&#160;	<b>Update Notice.</b> Merchant shall provide written notice to Payter of any changes to the information previously provided by Merchant to Payter, including, but not limited to, any additional locations, any change in business, any new business, the identity of principals and/or owners, the form of business organization, type of goods and services provided and method of conducting sales. Such notice must be received by Payter within five Business Days of the change. Merchant shall provide any additional information requested by Payter within five days of such request. Payter retains the right to: (a) review Merchant\'s Checks, files, and ACH Entries, return items, and business activities from time to time to confirm Merchant is conducting business as stated by Merchant at the time of the execution of this Agreement and (b) re-price or terminate Payter provided services based on changes to information previously provided to Payter by Merchant.
		<br>9.&#160;&#160;&#160;&#160;&#160;	<b>Financial Information.</b> Payter may from time to time request information from Merchant in order to evaluate a continuation of Payter provided services to be provided by Payter hereunder and/or adjustment of any limits set by this Agreement. Merchant agrees to provide the requested financial information immediately upon request by Payter, in the form required by Payter. Merchant authorizes Payter to investigate or reinvestigate at any time any information provided by Merchant in connection with this Agreement or Payter provided services and to request reports from credit bureaus and reporting agencies for such purpose. Upon request by Payter, Merchant hereby authorizes Payter to enter Merchant\'s business premises for the purpose of ensuring that Merchant is in compliance with this Agreement and to audit Merchant\'s ACH activities. If Merchant refuses to provide the requested financial information, or if Payter concludes, in its sole discretion, that the credit risk of Merchant is unacceptable, or if Merchant refuses to give Payter access to Merchant\'s premises, Payter may terminate Payter provided services according to the provisions hereof.
		<br>10.&#160;&#160;&#160;&#160;&#160;	<b>Fees and Charges.</b> Merchant agrees to pay to Payter the fees and charges set forth in the Merchant Application or provided from time to time hereafter to Merchant, and all such other fees and charges as may be agreed upon from time to time by Merchant and Payter. Payter will initiate ACH debit Entries to Merchant\'s Fee Account to collect the fees and charges for services provided. Should Merchant fail or refuse to pay any charges under this Agreement, Merchant agrees to pay all collection costs (including reasonable attorney\'s fees) which may be incurred by Payter. Payter shall have the right to increase or decrease charges imposed for Payter provided services and will notify Merchant of the changes. Merchant\'s use of Payter provided services after changes have been made shall constitute Merchant\'s agreement to the same. In addition to Payter provided services fees, Merchant agrees to pay all taxes, tariffs and assessments levied or imposed by any government agency in connection with Payter provided services, this Agreement, and/or the software or equipment made available to Merchant (excluding any income tax payable by Payter).
        <br>
		<h4>ACH TERMS AND CONDITIONS</h4>
		<br>11.&#160;&#160;&#160;&#160;&#160;	<b>ACH Services.</b> Merchant desires Payter to provide ACH processing services as part of Payter provided services as a Third Party Sender of transactions on behalf of Merchant. These ACH transactions ("<b>Entries</b>" or "<b>Entry</b>") will be processed pursuant to the terms of this Agreement, the operating rules of NACHA, and the applicable state and federal laws and regulations governing ACH transactions.
		<br>12.&#160;&#160;&#160;&#160;&#160;	<b>Authorizations.</b>
		<br>(a)&#160;&#160;&#160;&#160;&#160;	 	<b>MERCHANT WILL OBTAIN AUTHORIZATION FOR EACH ENTRY PRIOR TO DEBITING AND/OR CREDITING A CUSTOMER\'S ("RECEIVER\'S") ACCOUNT AND SHALL MAINTAIN RECORDS OF THE AUTHORIZATION NECESSARY TO RESOLVE DISPUTES FOR TWO YEARS.</b> Proper authorizations must be in written or oral format. Written authorizations include any agreements between Merchant and its customer and or any electronic signature that includes but is not limited to a digital signature or security code. Oral authorizations must be either (i) a tape recording of the oral authorization, or (ii) provide the customer with a written notice confirming the oral authorization prior to the Settlement Date of the Entry. Payments initiated through the Internet will have proper notification and authorization on the Web site. Merchant must maintain authorizations for a period of two years after the transaction. Payter reserves the right to request and review all authorized records. Upon request, Merchant shall furnish the original or a copy of the authorization to any affected Participating Depository Financial Institution, as defined in the Rules.
		<br>(b)&#160;&#160;&#160;&#160;&#160;	 	Merchant will utilize commercially reasonable methods to establish the identity of the Receiver, and hereby warrants to Payter that each such Receiver has authorized Merchant to submit ACH Entries to its account for settlement of transactions to which Receiver has agreed.
		<br>(c)&#160;&#160;&#160;&#160;&#160;	 	As required by the Rules, Merchant must use commercially reasonable procedures to verify that routing numbers are valid for all Entries
		<br>(d)&#160;&#160;&#160;&#160;&#160;		Merchant must conduct an annual audit to ensure that the financial information it obtains from Receiver is protected by security practices and procedures that include adequate levels of, (i) physical security to protect against theft, (ii) personnel and access controls, and (iii) network security.
		<br>13.&#160;&#160;&#160;&#160;&#160;	<b>Originator.</b> Merchant hereby agrees that Merchant is the "<b>Originator</b>", as that term is defined in the Rules, of the ACH Entries and hereby assumes all of the obligations and responsibilities of an Originator. Merchant shall establish policies and procedures to ensure that Merchant is in compliance with the Rules at all times. Merchant agrees that Payter or the Originating Depository Financial Institution may audit Merchant\'s ACH activities.
		<br>14.&#160;&#160;&#160;&#160;&#160;	<b>Merchant Representations and Warranties; Indemnity.</b> With respect to each and every Entry transmitted by Merchant, Merchant represents and warrants to Payter and agrees that (a) each person shown as the Receiver on an Entry received by Payter from Merchant has authorized the initiation of such Entry and the crediting or debiting of its account in the amount and on the Effective Entry Date shown on such Entry, (b) such authorization is operative at the time of transmittal or crediting or debiting by Payter as provided herein, (c) Entries transmitted to Payter by Merchant are limited to those types of credit and debit Entries set forth in the Merchant Application, (d) Merchant shall perform its obligations under this Agreement in accordance with all applicable laws, regulations, and orders, including, but not limited to, the sanctions laws, regulations, and orders administered by OFAC; laws, regulations, and orders administered by FinCEN; and any state laws, regulations, or orders applicable to the providers of ACH payment services, and (e) Merchant shall be bound by and comply with the provision of the Rules (among other provisions of the Rules) making payment of an Entry by the RDFI to the Receiver provisional until receipt by the RDFI of final settlement for such Entry. Merchant specifically acknowledges that it has received notice of the rule regarding provisional payment and of the fact that, if such settlement is not received, the RDFI shall be entitled to a refund from the Receiver of the amount credited and Merchant shall not be deemed to have paid the Receiver the amount of the Entry. Merchant shall indemnify Payter against any loss, liability or expense (including attorney\'s fees and costs) resulting from or arising out of any breach of any of the foregoing warranties, representations, or agreements.
		<br>15.&#160;&#160;&#160;&#160;&#160;	<b>Transmittal of Entries by Merchant.</b> Merchant or Authorized Merchant Representative(s) shall initiate the debit or credit Entries hereunder on behalf of and selected by Merchant on the Merchant Application on a Business Day. For the purposes of this Agreement, "<b>Business Day</b>" means Monday through Friday, excluding federal banking holidays. Merchant or Authorized Merchant Representative(s) shall transmit or deliver Entries to Payter in computer readable form to the location(s) specified by Payter and in compliance with the formatting and other requirements set forth in the NACHA file specifications or as otherwise specified by Payter. Merchant shall have the sole responsibility for the accuracy of the data transmitted to Payter including, but not limited to, the amount of the transaction, the bank routing number and the account number of the Receiver. Merchant acknowledges and agrees that if an inconsistency between a Receiver\'s name and account number exists, the transaction will be initiated based upon the account number even if it identifies a person different from the named Receiver. Merchant hereby agrees to be responsible and liable for any loss incurred by any party including, but not limited to, Payter, the Receiver, the RDFI, or the ODFI for any error in the data submitted by Merchant. Entries must be received by Payter before the Payter cut-off time ("<b>Cut-Off</b>") set forth in the Payter Procedures. Entries received after the Cut-Off shall be deemed to have been received on the next Business Day. The total dollar amount of Entries transmitted by Merchant to Payter on any one Business Day shall not exceed the limit established by Payter. Merchant may not reinitiate Entries except as prescribed by the Rules. Merchant further agrees to comply with batch and item limits set by Payter at its sole discretion. Payter will have no obligation to process Entries or batches that exceed the limits set.
		<br>16.&#160;&#160;&#160;&#160;&#160;	<b>Transaction Settlement.</b>
		<br>(a)&#160;&#160;&#160;&#160;&#160;			Payter and its affiliates shall establish an account with a financial institution selected by Payter and its affiliates and will hold the funds represented by the debit and credit Entries transmitted by Merchant until all preliminary return transactions have cleared and then the funds shall be transferred, via an ACH Credit, to either the Merchant\'s Depository Account or the Receiver\'s account, as applicable.
		<br>(b)&#160;&#160;&#160;&#160;&#160;			In the event Merchant wishes to initiate a credit Entry, Merchant shall either: 
		<br>&#160;&#160;&#160;&#160;&#160;  (i)&#160;&#160;&#160;&#160;&#160;	 	authorize Payter and its affiliates to debit Merchant\'s Depository Account upfront in an amount authorized by Merchant that would allow Merchant to originate multiple credit Entries up to the amount of the funds debited; or 
		<br>&#160;&#160;&#160;&#160;&#160;	(ii)&#160;&#160;&#160;&#160;&#160;	 	authorize Payter and its affiliates to debit Merchant\'s Depository Account for the amount of a specific credit Entry only.
		<br>(c)&#160;&#160;&#160;&#160;&#160;			For all Entries, the settlement amount paid to Merchant shall be net of any returned Entries. If any debit Entry is returned to Payter (in a timely manner as described by the Rules) and the settlement amount is not sufficient to accommodate the returned Entry, Payter and its affiliates will debit Merchant\'s Depository Account for the amount of the returned Entry plus fees and costs incurred by Payter and its affiliates. Merchant agrees to sign an authorization in the Merchant Application authorizing Payter and its affiliates to initiate an ACH debit to charge Merchant\'s Depository Account or the reserve account for debits relating to credit Entries as well as any returned Entries. <b>Payter and its affiliates reserve the right to extend the hold period on Merchant\'s funds should any questionable activity occur, or if Merchant\'s return rate increases enough to warrant a longer hold period as required by law or the Rules.</b> Merchant covenants and agrees that it shall be liable for any and all costs, charges and fees associated with returned Entries (whether due to a debit Entry Merchant originates or to a debit Entry Payter and its affiliates originate against Merchant\'s Depository Account). Merchant further covenants and agrees that it shall not revoke or rescind authorization for the debit Entries by Payter and its affiliates to Merchant\'s Depository Account.
		<br>17.&#160;&#160;&#160;&#160;&#160;	<b>Errors, Cancellations and Amendments to Entries.</b> Merchant shall notify Payter and its affiliates immediately of any Entry Merchant discovers it has initiated or authorized in error. Merchant shall have no right to cancel or amend any Entry after its receipt by Payter and its affiliates. However, Payter and its affiliates may, at its option, accept a cancellation or amendment by Merchant. If Payter accepts a cancellation or amendment of an Entry, Merchant must issue the cancellation or amendment in accordance with Payter and its affiliates\'s Security Procedure and Payter and its affiliates shall use reasonable efforts to act on the request by Merchant for cancellation of an Entry prior to transmitting it to the ODFI, but Payter and its affiliates shall have no liability if such cancellation is not effected. Merchant shall notify the Receiver of any reversing entry initiated to correct any Entry it has initiated in error. The notification to the Receiver must include the reason for the reversal and be made no later than the Settlement Date of the reversing entry. If Payter and its affiliates accepts a cancellation or amendment of an Entry, Merchant hereby agrees to indemnify, defend all claims and hold Payter and its affiliates harmless from any loss, damages, or expenses, including but not limited to attorneys\' fees, incurred by Payter and its affiliates as the result of its acceptance of the cancellation or amendment.
		<br>18.&#160;&#160;&#160;&#160;&#160;	<b>Error Detection.</b> Payter and its affiliates has no obligation to discover and shall not be liable to Merchant for errors made by Merchant, including but not limited to errors made in identifying the Receiver, or an Intermediary or Receiving Depository Financial Institution ("<b>RDFI</b>") or for errors in the amount of an Entry. Payter and its affiliates shall likewise have no duty to discover and shall not be liable for duplicate Entries issued by Merchant. Notwithstanding the foregoing, if Merchant discovers that any Entry it has initiated was in error, it shall notify the Payter and its affiliates of such error. If such notice is received no later than four hours prior to the ACH cutoff time, Payter and its affiliates will utilize reasonable efforts to initiate an adjusting entry within the time limits provided by the Rules. In the event that Merchant makes an error or issues a duplicate Entry, Merchant shall indemnify, defend all claims, and hold Payter and its affiliates harmless from any loss, damages, or expenses, including but not limited to attorney\'s fees, incurred by Payter and its affiliates as result of the error or issuance of duplicate Entries.
		<br>19.&#160;&#160;&#160;&#160;&#160;	<b>Returned/Rejected and Chargeback Items.</b> Merchant acknowledges that it is solely responsible for any and all returned or rejected items. Merchant hereby authorizes Payter and its affiliates to deduct the amount of any returned or rejected item and any associated processing fees from the balance of funds currently due to Merchant. In the event there are not sufficient funds currently held by Payter and its affiliates on Merchant\'s behalf, Merchant further authorizes Payter and its affiliates to debit the Depository Account or any other deposit account maintained by Merchant, as necessary, to recover any funds for returned or rejected debit transactions in accordance with the provisions of Section 11 of this Agreement. If a cardholder disputes any transaction, if a transaction is charged back for any reason by the card issuing institution, or if Payter or Member has any reason to believe an indebtedness previously purchased is questionable, not genuine, or is otherwise unacceptable\' the amount of such indebtedness may be charged back and deducted from any payment due to Merchant or may be charged against any of Merchant\'s accounts or the Reserve Account (as defined below). Merchant acknowledges and agrees that it is bound by the rules of the card associations and network organizations with respect to any chargeback. Merchant further acknowledges that it is solely responsible for providing Payter and Member with any available information to re-present a chargeback and that, regardless of any information it provides or does not provide Payter and Member in connection with a chargeback, or any other reason, Merchant shall be solely responsible for the liability related to such chargeback. A list of some common reasons for chargebacks is contained in the Card Acceptance Guide provided, however, that such list is not exclusive and does not limit the generality of the foregoing. If any such amount is uncollectible through withholding from any payments due hereunder or through charging Merchant\'s accounts or the Reserve Account, Merchant shall, upon demand by Payter, pay Payter the full amount of the chargeback. Merchant understands that obtaining an authorization for any sale shall not constitute a guarantee of payment, and such sales slips can be retuned or charged back to Merchant like any other item hereunder.
		<br>20.&#160;&#160;&#160;&#160;&#160;	<b>Delay or Failure to Transfer Funds.</b> Payter and its affiliates shall not be liable to Merchant or Receiver for any damages of any kind for any delay in payment, including special, consequential, punitive, or indirect loss or damage. Payter and its affiliates shall not be liable or responsible to Merchant for any delay or failure to transfer any amount hereunder for any reason including but not limited to rules, regulations, or policies of the Federal Reserve Board which place an aggregate limit on the amount Bank can transfer from time to time during any banking day. In no event shall Payter and its affiliates be liable to Merchant for attorney\'s fees incurred by Merchant in any action brought by Merchant under this Agreement.
		<br>21.&#160;&#160;&#160;&#160;&#160;	<b>Data Retention.</b> Merchant shall retain data on file adequate to permit remaking of Entries for 10 days following the date of their transmittal by Payter and its affiliates as provided herein, and shall provide such data to Payter and its affiliates upon its request. Without limiting the generality of the foregoing provisions, Merchant specifically agrees to be bound by and comply with all applicable provisions of the Rules regarding the retention of documents or any record, including, without limitation, Merchant\'s responsibilities to retain all items, source documents, and records of authorization in accordance with the Rules.
		<br>22.&#160;&#160;&#160;&#160;&#160;	<b>Rejection of Entries.</b> Payter and its affiliates may reject any transaction or file of transactions which does not comply with the requirements of this Agreement and may reject any transaction if Merchant is not otherwise in compliance with the terms of the Agreement. Payter and its affiliates has no obligation to notify Merchant of the rejection of an Entry but Payter may do so at its option. Payter and its affiliates shall have no liability to Merchant for rejection of an Entry nor for any failure to notify Merchant of the rejection of an Entry. In the event any transactions are rejected by the ODFI or Payter and its affiliates for any reason whatsoever, it shall be the responsibility of Merchant to remake such Entries. Merchant shall retain and provide Payter and its affiliates, upon request, all information necessary to remake any Entry or file of Entries within 10 business days after the Settlement date. 
        <br>
		<h4>CARD PROCESSING SERVICES</h4>
		<br>23.&#160;&#160;&#160;&#160;&#160;	<b>Credit Card Gateway.</b> Merchant desires Payter to forward credit card transactions to Merchant\'s credit card processor. Merchant acknowledges and agrees that Payter\'s sole responsibility under this Agreement to Merchant as it relates to credit card transactions is that Payter shall send credit card transactions transmitted by Merchant to Merchant\'s credit card processor. Merchant further acknowledges that Payter shall not perform any type of edit or review of the credit card transactions and shall transmit them to Merchant\'s credit card processor in the same format and condition as the transactions were received from Merchant. Payter will not settle for any credit card transactions received from Merchant and will not process any credit card transactions refused or returned by Merchant\'s credit card processor. Merchant will incur SEPARATE charges from Merchant\'s credit card processor for the servicing of its credit card merchant account as documented in the agreement between Merchant and Merchant\'s credit card processor. Merchant understands that Payter is not a party to that Agreement, and that the rates, fees, and charges associated with its merchant account are strictly between Merchant and Merchant\'s credit card processor. Additionally, in the event that Merchant enters into a lease or financing terms, Merchant understands that Payter is not a party to that Agreement, and that the terms and conditions of the lease or financing is strictly between Merchant, the lease/finance Merchant, and Merchant\'s credit card processor, acting independently of Payter.
		<b>23.1 	Certain Merchant Responsibilities.</b>
		<br>23.1.1 	Merchant agrees to participate, and to cause third parties acting as Merchant\'s agent ("Agents"), to participate, in the Associations in compliance with, and subject to, the by-laws, operating regulations and/or all other rules, policies and procedures of the Associations (collectively "Operating Regulations"). Merchant also agrees to comply with all applicable state, federal, and local laws, rules, and regulations ("Laws"). Without limiting the foregoing, Merchant agrees that it will fully comply with any and all confidentiality and security requirements of the USA Patriot Act (or similar law, rule or regulation), VISA, MasterCard, Discover, and/or Other Networks, including but not limited to the Payment Card Industry Data Security Standard, the VISA Cardholder Information Security Program, the MasterCard Site Data Protection Program, and any other program or requirement that may be published and/or mandated by the Associations. For purposes of this section, Agents include, but are not limited to, Merchant\'s software providers and/or equipment providers.
		<br>23.1.2 	If appropriately indicated on Merchant\'s application attached hereto, Merchant may be a limited acceptance Merchant, which means that Merchant has elected to accept only certain Visa and MasterCard card types (i.e., consumer credit, consumer debit, and commercial cards) and must display appropriate signage to indicate the same. Payter and its associated credit card Acquirer ("Acquirer") have no obligation other than those expressly provided under the Operating Regulations and applicable law as they may relate to limited acceptance. Merchant, and not Payter or Acquirer, will be solely responsible for the implementation of its decision for limited acceptance, including but not limited to policing the card type(s) accepted at the point of sale.
		<br>23.1.3 	Merchant shall only complete sales transactions produced as the direct result of bona fide sales made by Merchant to cardholders, and is expressly prohibited from processing, factoring, laundering, offering, and/or presenting sales transactions which are produced as a result of sales made by any person or entity other than Merchant, or for purposes related to financing terrorist activities.
		<br>23.1.4 	Merchant may set a minimum transaction amount to accept a card that provides access to a credit account, under the following conditions: i) the minimum transaction amount does not differentiate between card issuers; ii) the minimum transaction amount does not differentiate between MasterCard, Visa, or any other acceptance brand; and iii) the minimum transaction amount does not exceed ten dollars (or any higher amount established by the Federal Reserve).  Merchant may set a maximum transaction amount to accept a card that provides access to a credit account, under the following conditions:
		Merchant is a 
		<br>i) 		department, agency or instrumentality of the U.S. government; 
		<br>ii) 	corporation owned or controlled by the U.S. government; or 
		<br>iii) 	Merchant whose primary business is reflected by one of the following MCCs: 8220, 8244, 8249 - Schools,
		Trade or Vocational; and the maximum transaction amount does not differentiate between MasterCard, Visa, or any other acceptance brand.
		<br><b>23.2  Merchant Prohibitions.</b>
		Merchant must not 
		<br>i) 		require a cardholder to complete a postcard or similar device that includes the cardholder\'s account number, card expiration date, signature, or any other card account data in plain view when mailed, 
		<br>ii) 	add any tax to transactions, unless applicable law expressly requires that a Merchant impose a tax (any tax amount, if allowed, must be included in the transaction amount and not collected separately), iii) request or use an account number for any purpose other than as payment for its goods or services, iv) disburse funds in the form of travelers checks if the sole purpose is to allow the cardholder to make a cash purchase of goods or services from Merchant, v) disburse funds in the form of cash unless Merchant is dispensing funds in the form of travelers checks, TravelMoney cards, or foreign currency (in such case, the transaction amount is limited to the value of the travelers checks, TravelMoney cards, or foreign currency, plus any commission or fee charged by the Merchant), or Merchant is participating in a cash back service, vi) submit any transaction receipt for a transaction that was previously charged back to the Acquirer and subsequently returned to Merchant, irrespective of cardholder approval, vii) accept a Visa consumer credit card or commercial Visa product issued by a U.S. issuer to collect or refinance an existing debt, viii) accept a card to collect or refinance an existing debit that has been deemed uncollectable by Merchant, or ix) submit a transaction that represents collection of a dishonored check. Merchant further agrees that, under no circumstance, will Merchant store cardholder data in violation of the Laws or the Operating Regulations including but not limited to the storage of track-2 data. Neither Merchant nor its Agent shall retain or store magnetic-stripe data subsequent to the authorization of a sales transaction.
		<br><b>23.3  Settlement.</b>
		Upon receipt of Merchant\'s sales data for card transactions through Payter\'s Services, Acquirer will process Merchant\'s sales data to facilitate the funds transfer between the various Associations and Merchant.  After Acquirer receives credit for such sales data, Acquirer will fund Merchant, either directly to the Merchant-Owned Designated Account or through Payter to an account designated by Payter ("Payter Designated Account"), at Acquirer\'s sole option, for such card transactions. Merchant agrees that the deposit of funds to the Payter Designated Account shall discharge Acquirer of its settlement obligation to Merchant, and that any dispute regarding the receipt or amount of settlement shall be between Payter and Merchant. Acquirer will debit the Payter Designated Account for funds owed to Acquirer as a result of the Services provided hereunder, unless a Merchant-owned account is otherwise designated below. Further, if a cardholder disputes a transaction, if a transaction is charged back for any reason, or if Payter or Acquirer reasonably believe a transaction is unauthorized or otherwise unacceptable, the amount of such transaction may be charged back and debited from Merchant if settled to Merchant-owned account or debited from the Payter Designated Account if settled to that account.
        <br>
		<h4>GENERAL TERMS AND CONDITIONS</h4>
		<br>24.&#160;&#160;&#160;&#160;&#160;	<b>Merchant General Warranties.</b> Merchant represents, warrants and covenants the following to Payter:
		<br>(a)&#160;&#160;&#160;&#160;&#160;			<u>Information.</u> All information provided by Merchant to Payter is true, complete and accurate and properly reflects the business, financial condition and principal partners, owners or officers, of Merchant. Merchant is not engaged in, or affiliated with, any businesses, products or methods of selling other than those disclosed by Merchant to Payter;
		<br>(b)&#160;&#160;&#160;&#160;&#160;			<u>Authority and Legality.</u>
		<br>(i) 	Merchant is authorized to enter into, and perform its obligations under, this Agreement; 
		<br>(ii) 	the person signing this Agreement on behalf of Merchant is duly authorized to execute this Agreement; 
		<br>(iii) 	this Agreement is valid and enforceable against Merchant in accordance with its terms; and 
		<br>(iv) 	the entry into, and performance of, this Agreement by Merchant will not violate any law, or conflict with any other agreement, to which Merchant is subject;
		<br>(c)&#160;&#160;&#160;&#160;&#160;			<u>No Litigation.</u> There is no action, suit or proceeding pending or, to Merchant\'s knowledge, threatened which, if decided adversely, would impair Merchant\'s ability to carry on its business substantially as now conducted or which would adversely affect Merchant\'s financial condition or operations;
		<br>(d)&#160;&#160;&#160;&#160;&#160;			<u>Rule Compliance.</u> Merchant conducts its business, and submits Checks, Entries, and files in compliance with this Agreement, the Payter Procedures, the laws of the United States and other applicable law and the Rules;
		<br>(e)&#160;&#160;&#160;&#160;&#160;			<u>Loss Recovery.</u> Merchant agrees to undertake reasonable efforts to cooperate, as permitted by applicable law, in performing loss recovery efforts in connection with any actions Payter or the Originating Depository Financial Institution may be obligated to defend or elect to pursue against a third party.
		<br>25.&#160;&#160;&#160;&#160;&#160;	<b>No Warranties.</b> MERCHANT ACKNOWLEDGES AND AGREES THAT Merchant\'s USE OF Payter PROVIDED SERVICES SHALL BE AT Merchant\'s SOLE RISK, AND THAT Payter PROVIDED SERVICES IS PROVIDED BY Payter ON AN "AS IS" BASIS. Payter MAKE NO REPRESENTATIONS OR WARRANTIES WHATSOEVER, EXPRESS OR IMPLIED, IN LAW OR IN FACT, TO MERCHANT OR TO ANY OTHER PERSON, AS TO Payter PROVIDED SERVICES OR ANY ASPECT THEREOF, INCLUDING (WITHOUT LIMITATION) ANY WARRANTY OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT, AND Payter HEREBY DISCLAIMS ANY AND ALL OF THE SAME. MERCHANT AGREES THAT NO ORAL OR WRITTEN ADVICE OR REPRESENTATION OBTAINED FROM ANY Payter EMPLOYEE OR REPRESENTATIVE SHALL CREATE A WARRANTY OR REPRESENTATION FOR PURPOSES OF THIS AGREEMENT OR Payter PROVIDED SERVICES TO BE PERFORMED PURSUANT HERETO.
		<br>26.&#160;&#160;&#160;&#160;&#160;	<b>Limitation of Liability.</b> TO THE FULLEST EXTENT PERMITTED BY LAW, Payter\'s AND ITS CONTRACTORS\', SUPPLIERS\' AND RESELLERS\' TOTAL LIABILITY TO MERCHANT AND ANY THIRD PARTIES UNDER THIS AGREEMENT WILL BE LIMITED TO THE PAYMENTS MADE BY MERCHANT DURING THE PREVIOUS 12 MONTHS FOR Payter PROVIDED SERVICES. IN NO EVENT WILL Payter, ITS CONTRACTORS\', SUPPLIERS\' OR RESELLERS BE LIABLE TO MERCHANT FOR ANY INDIRECT, SPECIAL, INCIDENTAL, EXEMPLARY PUNITIVE, TREBLE OR CONSEQUENTIAL DAMAGES (INCLUDING, WITHOUT LIMITATION, LOSS OF BUSINESS, REVENUE, PROFITS, GOODWILL, USE, DATA, OR OTHER ECONOMIC ADVANTAGE), WHETHER BASED ON BREACH OF CONTRACT, TORT (INCLUDING NEGLIGENCE), PRODUCT LIABILITY, OR OTHERWISE, AND WHETHER OR NOT Payter HAS PREVIOUSLY BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. NO CLAIM ARISING OUT OF THIS AGREEMENT, REGARDLESS OF FORM, MAY BE BROUGHT MORE THAN THE SHORTER OF TWO YEARS OR THE MINIMUM PERIOD ALLOWED BY LAW AFTER THE CAUSE OF ACTION HAS OCCURRED. THIS SECTION SHALL SURVIVE FAILURE OF ANY EXCLUSIVE REMEDY.
		<br>27.&#160;&#160;&#160;&#160;&#160;	<b>Indemnification and Liability; Third Party Claims.</b> Merchant hereby agrees to indemnify Payter and each of its parents, subsidiaries and affiliates and their respective officers, directors, employees, members, partners, agents, insurers and attorneys (each an "<b>Indemnified Party</b>" and, collectively, the "<b>Indemnified Parties</b>") for, and holds each of the Indemnified Parties harmless from and against, all actions, causes of action, claims, damages, liabilities and expenses (including reasonable attorneys\' fees and or collection fees) of any nature or kind (including those by third parties) arising out of, or related to, this Agreement, including all actions, causes of action, claims, damages, liabilities and expenses arising out of, related to or resulting from: (a) Merchant\'s (i) failure to report required changes, (ii) transmission of incorrect data to Payter, (iii) failure to maintain compliance with the Rules, (iv) depositing a Prohibited Check or an electronic representation of a substitute check; (b) (i) Payter\'s provision of Payter provided services, (ii) Payter\'s action or inaction in accordance with, or in reliance upon, any instructions or information received from any person reasonably believed by Payter to be an authorized representative of Merchant, (c) Merchant\'s breach of any of Merchant\'s representations, warranties, covenants or other agreements or responsibilities under this Agreement and/or (d) Merchant\'s breach or violation of any Rules; provided, however, Merchant is not obligated to indemnify Payter for any damages solely and proximately caused by Payter\'s gross negligence or willful misconduct.
		<br>28.&#160;&#160;&#160;&#160;&#160;	<b>Confidential Information and Proprietary Right in Data.</b> All information of a business nature relating to the assets, liabilities or other business affairs disclosed to Payter by Merchant in connection with this Agreement is confidential. Except when allowed by applicable law, Payter shall not disclose or permit access to any such information by any person, firm or corporation. Payter shall take such action as shall be reasonably necessary to preserve and protect the confidentiality of such information. Merchant agrees to hold confidential, and to use only in connection with Payter provided services, all information furnished to Merchant by Payter or by third parties from whom Payter has secured the right to use in support of Payter provided services, including, but not limited to, Payter\'s product and service pricing structure, system design, programming techniques or other unique techniques. In addition, should Merchant at any time receive or acquire any information relating to another Payter customer, Merchant shall promptly return such information to Payter and not reveal such information to any other party and shall not make use of such information for its own benefit or otherwise. Payter\'s and Merchant\'s obligations and agreements under this paragraph shall not apply to any information supplied that was known to either party prior to the disclosure by the other, is or becomes generally available to the public other than by breach of this Agreement or otherwise becomes lawfully available on a non-confidential basis from a third party who is not under an obligation of confidence to either party. Notwithstanding anything to the contrary contained herein, it is understood and agreed by the parties hereto that the performance of Payter provided services is or might be subject to regulation and examination by authorized representatives of the Comptroller of the Currency, the Board of Governors of the Federal Reserve System, the Board of Directors of the Federal Deposit Insurance Corporation and/or a state regulatory agency, and Merchant agrees to the release of by Payter of Merchant\'s reports, information, assurances and other data and information as may be required under applicable laws and regulations. This clause shall survive the termination of the Agreement.
		<br>29.&#160;&#160;&#160;&#160;&#160;	<b>Arbitration and Waiver of Jury Trial.</b> Merchant and Payter agree that the transactions contemplated in this Agreement involve "commerce" under the Federal Arbitration Act ("<b>FAA</b>"). <b>EVERY CONTROVERSY OR CLAIM BETWEEN MERCHANT AND ANY INDEMNIFIED PARTY ARISING OUT OF, OR IN ANY WAY RELATED TO OR RESULTING FROM, THIS AGREEMENT, Payter PROVIDED SERVICES OR ANY OTHER SERVICES PROVIDED BY Payter, WHETHER BASED IN CONTRACT, TORT OR ANY OTHER LEGAL THEORY, INCLUDING CLAIMS OF FRAUD, SUPPRESSION, MISREPRESENTATION AND FRAUD IN THE INDUCEMENT, WILL BE RESOLVED BY BINDING ARBITRATION UNDER THE FAA.</b> The arbitration will be administered by the American Arbitration Association ("<b>AAA</b>") under its Commercial Arbitration Rules (the "<b>Arbitration Rules</b>"). <b>IF A CLAIM IS SUBMITTED TO ARBITRATION, (A) MERCHANT WILL NOT HAVE THE RIGHT TO GOTO COURT OR TO HAVE A JURY TRIAL; (B) MERCHANT WILL NOT HAVE THE RIGHT TO ENGAGE IN PRE-ARBITRATION DISCOVERY EXCEPT AS PROVIDED IN THE ARBITRATION RULES; (C) MERCHANT WILL NOT HAVE THE RIGHT TO HAVE ANY CLAIM ARBITRATED AS A CLASS ACTION UNDER THE ARBITRATION RULES OR UNDER ANY OTHER RULES, WHETHER OF CIVIL PROCEDURE OR OTHERWISE; AND (D) THE ARBITRATOR\'S DECISION WILL BE FINAL AND BINDING WITH LIMITED RIGHTS TO APPEAL. THIS ARBITRATION PROVISION IS SUPPLEMENTAL TO, AND NOT IN LIEU OF, ANY OTHER ALTERNATIVE DISPUTE RESOLUTION PROVISION, AND, IN THE EVENT OF A CONFLICT BETWEEN THIS PROVISION AND ANY OTHER SUCH ALTERNATIVE DISPUTE RESOLUTION PROVISION, THE TERMS OF THIS PROVISION SHALL CONTROL.</b> This agreement to arbitrate disputes will survive the termination this Agreement.
		<br>30.&#160;&#160;&#160;&#160;&#160;	<b>Termination.</b> This Agreement shall remain in full force and effect from the date hereof until such time as this Agreement is terminated by either party as hereinafter provided:
		<br>(a) 	this Agreement may be terminated at any time by either party following 30 days\' prior written notice;
		<br>(b) 	either party shall have the right to terminate this Agreement immediately by giving written notice to the other if such other party: (i) ceases to conduct its business in the ordinary sense, (ii) has any substantial part of its property become subject to any levy, seizure, assignment or application for sale for, or by, any creditor or government agency, (iii) is a party to an acquisition or (iv) in the reasonable judgment of the party seeking termination, experiences an adverse change in its financial condition or business which impairs the ability of such party to perform its obligations under this Agreement, (v) fails to perform its obligations under this Agreement or defaults under any other agreement between the parties, (vi) makes any warranty or representation which proves to be false or misleading. (vii) Merchant has the right to terminate at any point in time.
		<br>(c) 	Notwithstanding the foregoing, Payter may immediately terminate this Agreement without notice if, in Payter\'s sole discretion, Payter determines that Merchant has abused Payter provided services, violated the Rules, regulations, or laws, or Payter believes that it will suffer a loss or other damage if the Agreement is not terminated. Payter\'s election to terminate this Agreement is in addition to any and all other remedies that may be available to Payter and will not affect any obligations Merchant may have to Payter.
		<br>31.&#160;&#160;&#160;&#160;&#160;	<b>Other.</b>
		<br>(a) 	<u>Attorneys\' Fees.</u> In the event of any arbitration or other adversarial proceeding between the parties concerning this Agreement, if Payter is the prevailing party Payter shall be entitled to recover its reasonable attorneys\' fees, collection fees and other costs in addition to any other relief to which it may be entitled.
		<br>(b) 	<u>Successors.</u> This Agreement and all the terms and provisions herein shall be binding upon, and shall inure to the benefit of, the parties hereto and their respective successors and assigns.
		<br>(c) 	<u>Assignment.</u> No right or interest hereby conferred shall be assignable without the prior written consent of the other party, and any assignment made without such consent shall be null and void; provided, however that Payter may assign this Agreement or any part of it to any of Payter\'s affiliates or to a successor of Payter by merger or acquisition upon written notice to Merchant.
		<br>(d) 	<u>Amendments.</u> Payter may amend the terms of this Agreement at any time, in its sole discretion, by giving notice to Merchant. If required by this Agreement or by applicable law, notice will be given for the applicable required number of days in advance of each such amendment. Merchant\'s continued use of Payter provided services shall constitute Merchant\'s agreement to such amendments. No amendments requested by Merchant shall be effective unless received, and agreed to in writing, by Payter. 
		<br>(e) 	<u>No Third Party Beneficiaries.</u> This Agreement shall not be construed to confer any rights or remedies upon any person not a party to this Agreement, whether as a third party beneficiary or otherwise, against Merchant or Payter, their respective successors, assigns and affiliates. 
		<br>(f) 	<u>Captions and Headings.</u> The captions and headings contained in this Agreement are for convenience of reference only and shall not be used to limit the applicability or meaning of any provisions of this Agreement. 
		<br>(g) 	<u>Entire Agreement.</u> Merchant agrees that this Agreement is the entire statement of the terms and conditions which apply to the subject matter hereof. This Agreement supersedes any prior agreements between the parties relating to Payter provided services. 
		<br>(h) 	<u>No Waiver.</u> No delay or omission in the exercise by either party of any right or remedy under this Agreement shall impair any such right or remedy or be construed to be a waiver thereof. 
		<br>(i) 	<u>Severability.</u> If any provision of this Agreement is held to be unenforceable, the other provisions shall not be affected, unless it can be reasonably assumed that the parties would not have made the agreement without such provision. 
		<br>(j) 	<u>Construction.</u> This Agreement is an agreement between parties who are experienced in sophisticated and complex matters similar to the transactions contemplated by this Agreement, is entered into by both parties in reliance upon the economic and legal bargains contained herein, and shall be interpreted and construed in a fair and impartial manner, without regard to such factors as the party which prepared the instrument or drafted any provision thereof, the relative bargaining powers of the parties or the domicile of any party. 
		<br>(k) 	<u>Survival.</u> Payter and Merchant agree that Sections 1, 10, 14, 17, 18, 24, 25, 36, 38, 39, 40, 41, 42, 43, 45(a), 45(e), 45(g), and 45(l) shall survive the termination of this Agreement. 
		<br>(l) 	<u>Governing Law.</u> This Agreement shall be governed by, and construed in accordance with, the laws of the State of Utah, without reference to its conflict of laws provisions, and applicable federal law. 
		<br>(m) 	<u>Relationship of Parties.</u> Merchant hereby agrees that Payter shall each be independent contractors in the performance of their obligations under this Agreement, and nothing contained herein shall be deemed to constitute either party as the agent, representative or franchisee of the other party, or both parties as joint venturers or partners for any purpose. 
		<br>(n) 	<u>Notices.</u> Any notice required or permitted to be sent under this Agreement shall be delivered by hand, by overnight courier, by facsimile, or by registered mail, return receipt requested, to the address of the parties first set forth in this Agreement or to such other address of the parties designated in writing in accordance with this subsection. 
		<br>(o) 	<u>Force Majeure.</u> Except for the obligation to make payments, nonperformance by either party will be suspended to the extent it is rendered impossible due to force majeure or other causes beyond such party\'s reasonable control and without such party\'s negligent or willful misconduct. 
		<br>(p) 	Merchant understands and accepts that Payter and its affiliates are not responsible for the success or failure of Merchant\'s business, or the success or failure of Merchant\'s on-line site. 
		<br>33.&#160;&#160;&#160;&#160;&#160;	<b>Card brand graduation process.</b>
		Once you reach $100K in annual Visa Volume or $1MM in annual MasterCard volume, you will be considered a "direct merchant" of Acquirer, in accordance with Payment Brand regulations.
		Merchant may be converted from the American Express Program to a direct Card acceptance relationship with American Express if and when Merchant has either (i) greater than $1,000,000 in Charge Volume in a rolling twelve (12) month prior or (ii) greater than $1,000,000 in Charge Volume in any three (3) consecutive months (hereinafter "High CV Merchant"). Upon conversion, (i) the Merchant will be bound by American Express\' then-current Card Acceptance Agreement; and (ii) American Express will set pricing and other fees payable by the Merchant for Card acceptance. 
		<br>34.&#160;&#160;&#160;&#160;&#160;	<b>CARD PROCESSING SERVICES</b>
		<br><b>34.1 Certain Merchant Responsibilities.</b>
		<br>34.1.1 Merchant agrees to participate, and to cause third
		Parties acting as Merchant\'s agent ("Agents"), to participate, in the Associations in compliance with, and subject to, the by-laws, operating regulations and/or all other rules, policies and procedures of the Associations (collectively "Operating
		Regulations"). Merchant also agrees to comply with all applicable state, federal, and local laws, rules, and regulations ("Laws").
		Without limiting the foregoing, Merchant agrees that it will fully comply with any and all confidentiality and security requirements of the USA Patriot Act (or similar law, rule or regulation), VISA,
		MasterCard, Discover, and/or Other Networks, including but not limited to the Payment Card Industry Data Security Standard, the
		VISA Cardholder Information Security Program, the MasterCard Site Data Protection Program, and any other program or requirement that may be published and/or mandated by the
		Associations. For purposes of this section, Agents include, but are not limited to, Merchant\'s software providers and/or equipment providers.
		<br>34.1.2 If appropriately indicated on Merchant\'s application attached hereto, Merchant may be a limited acceptance
		Merchant, which means that Merchant has elected to accept only certain Visa and MasterCard card types (i.e., consumer credit, consumer debit, and commercial cards) and must display appropriate signage to indicate the same. Payter and its associated credit card Acquirer ("Acquirer") have no obligation other than those expressly provided under the
		Operating Regulations and applicable law as they may relate to limited acceptance. Merchant, and not Payter or Acquirer, will be solely responsible for the implementation of its decision for limited acceptance, including but not limited to policing the card type(s) accepted at the point of sale.
		<br>34.1.3 Merchant shall only complete sales transactions produced as the direct result of bona fide sales made by Merchant to cardholders, and is expressly prohibited from processing, factoring, laundering, offering, and/or presenting sales transactions which are produced as a result of sales made by any person or entity other than Merchant, or for purposes related to financing terrorist activities.
		<br>34.1.4 Merchant may set a minimum transaction amount to accept a card that provides access to a credit account, under the following conditions: i) the minimum transaction amount does not differentiate between card issuers; ii) the minimum transaction amount does not differentiate between MasterCard,
		Visa, or any other acceptance brand; and iii) the minimum transaction amount does not exceed ten dollars (or any higher amount established by the Federal Reserve). Merchant may set a maximum transaction amount to accept a card that provides access to a credit account, under the following conditions:
		Merchant is a 
		<br>i) 		department, agency or instrumentality of the U.S. government; 
		<br>ii) 	corporation owned or controlled by the U.S. government; or 
		<br>iii) 	Merchant whose primary business is reflected by one of the following MCCs: 8220, 8244, 8249 - Schools, Trade or Vocational; and the maximum transaction amount does not differentiate between MasterCard, Visa, or any other acceptance brand.
		<br><b>34.2 Merchant Prohibitions.</b>
		Merchant must not 
		<br>i) 		require a cardholder to complete a postcard or similar device that includes the cardholder\'s account number, card expiration date, signature, or any other card account data in plain view when mailed, 
		<br>ii) 	add any tax to transactions, unless applicable law expressly requires that a Merchant impose a tax
		(any tax amount, if allowed, must be included in the transaction
		amount and not collected separately), 
		<br>iii) 	request or use an account number for any purpose other than as payment for its goods or services, 
		<br>iv) 	disburse funds in the form of travelers checks if the sole purpose is to allow the cardholder to make a cash purchase of goods or services from Merchant, v) disburse funds in the form of cash unless Merchant is dispensing funds in the form of travelers checks, TravelMoney cards, or foreign currency (in such case, the transaction amount is limited to the value of the travelers checks, TravelMoney cards, or foreign currency, plus any commission or fee charged by the Merchant), or Merchant is participating in a cash back service, vi) submit any transaction receipt for a transaction that was previously charged back to the Acquirer and subsequently returned to Merchant, irrespective of cardholder approval, vii) accept a Visa consumer credit card or commercial Visa product issued by a U.S. issuer to collect or refinance an existing debt, viii) accept a card to collect or refinance an existing debit that has been deemed uncollectable by Merchant, or ix) submit a transaction that represents collection of a dishonored check. Merchant further agrees that, under no circumstance, will Merchant store cardholder data in violation of the Laws or the Operating Regulations including but not limited to the storage of track-2 data. Neither Merchant nor its Agent shall retain or store magnetic-stripe data subsequent to the authorization of a sales transaction.
		<br>35.&#160;&#160;&#160;&#160;&#160;	<b>COMPLIANCE WITH RULES, REGULATIONS AND LAWS.</b>
		In performing its duties under this Agreement, each party agrees to comply with all applicable Rules, Regulations and Laws, including but not limited to any applicable data security requirements under the PCI-DSS Standards. Payter bears no responsibility for any lack of compliance with these
		Rules and Regulations by Merchant and directs Merchant to seek the counsel of outside legal assistance should Merchant have questions or concerns regarding compliance with such.
		Merchant agrees to cooperate and provide information requested by Payter to facilitate Payter\'s compliance with any applicable Law, Rule or Regulation. Additionally, Merchant shall reimburse Payter for any fines or loss of funds imposed on
		Payter for any violation of applicable Rules, Regulations, laws or the PCI Data Security Standards by Merchant.
		<br>36.&#160;&#160;&#160;&#160;&#160;	<b>Settlement.</b>
		Upon receipt of Merchant\'s sales data for card transactions through Payter\'s Services, Acquirer will process Merchant\'s sales data to facilitate the funds transfer between the various
		Associations and Merchant. After Acquirer receives credit for such sales data, Acquirer will fund Merchant, either directly to the Merchant-Owned Designated Account or through Payter to an account designated by Payter ("Payter Designated Account"), at
		Acquirer\'s sole option, for such card transactions. Merchant agrees that the deposit of funds to the Payter Designated Account shall discharge Acquirer of its settlement obligation to Merchant, and that any dispute regarding the receipt or amount of settlement shall be between Payter and Merchant. Acquirer will debit the Payter Designated Account for funds owed to Acquirer as a result of the Services provided hereunder, unless a
		Merchant-owned account is otherwise designated below.
		Further, if a cardholder disputes a transaction, if a transaction is charged back for any reason, or if Payter or Acquirer reasonably believe a transaction is unauthorized or otherwise unacceptable, the amount of such transaction may be charged back and debited from Merchant if settled to Merchant-owned account or debited from the Payter Designated Account if settled to that account.
		<br>37.&#160;&#160;&#160;&#160;&#160;	<b>ELECTRONIC SIGNATURES.</b>
		Under the Electronic Signatures in Global and National
		Commerce Act (E-Sign), this Merchant Services Agreement and all electronically executed documents related hereto are legally binding in the same manner as are hard copy documents executed by hand signature when 
		(1) 	your electronic signature is associated with the Merchant Services
		Agreement and related documents, 
		(2) 	you consent and intend to be bound by the Merchant Services Agreement and related documents, and 
		(3) 	the Merchant Services
		Agreement is delivered in an electronic record capable of retention by the recipient at the time of receipt (i.e., print or otherwise store the electronic record). This Merchant
		Services Agreement and all related electronic documents shall be governed by the provisions of E-Sign.

	</p>
</div>


</body>
</html>
';
?>